### PR TITLE
V1.2 candidate

### PR DESCRIPTION
**Pull request by timchurches**
Max,

This pull request merges all the changes I've made, with bug fixes and with your sequencer. I haven't documented all the changes yet, but will do so at https://github.com/mxmxmx/O_C/wiki/V1.2-documentation,-under-construction over the next few days. I should have time to do a few hours more testing on Monday 19 Dec or Tuesday 20 Dec.

Tim C

### CODE REVIEW

**Comment by mxmxmx** [comment]
ok, merged. what about the dual sequencer?

**Comment by timchurches** [comment]
The dual sequencer is there and enabled. I renamed it Sequins but feel free to change the name. I'll work on documentation today and testing on Tuesday. I'm going to Japan for two weeks at the end of this week but will have some time to spend on it until then, I hope, although I should be brushing up on my Japanese.

----
t

**Comment by mxmxmx** [comment]
oh, i meant the dual quantizer. i can do some testing tomorrow. anything to look out for specifically?
and have in japan then.

**Comment by timchurches** [comment]
Yeah, it would be cool to include the dual quantiser, even if it just as a
first pass. I tested it and it seemed to work nicely, but I didn't merge
its branch. I didn't have time to look, but you mentioned that it blows
away the calibration data. I only installed it on my original O&C which
still has trimpots etc, and didn't bother to check what happened to the
calibration. Note that in the pull request that you just merged, the
settings data area has been increased to 1400 bytes. It was 768 bytes, but
that didn't leave enough for two copies so might as well increase it to use
up the available EEPROM storage. So now that is still about 700 bytes of
storage still available for apps. No change was made to the calibration and
global config data area - is that where the dual quantiser app writes? It
may be a bit problematic if it needs to clobber the calibration data,
because quite a few owners seemed to have purchased built ones without any
record of what the calibration values should be, and without access to a
decent DMM to recalibrate.

Several new sources were added to the ASR but I think the menu item hiding
may not work correctly all the time, for reasons I don't understand. It
seems like it needs a menu refresh call somewhere, but I can't work out
where. I'll work on the documentation for the new stuff this afternoon,
which will make it clearer which are new areas which warrant testing.

Yeah, another holiday....sigh. Anyway, I hope to visit the guys at
Clockface Modular in Tokyo - someone from the Australia ,modular synth
group on Facebook was describing O&C to them and said they were very keen
to try one out, so I'll take my original one with me that they can have
(hmmm, I'd better remove the trimpots etc first).

Tim C

**Comment by mxmxmx** [comment]
oh, i guess i misunderstood the consequences of changing the eeprom settings then. there should be no difference in terms of settings data between the sequencer branch and the DQ_test branch. 
i just merged your commits into that branch, too.

i can double-check the calibration stays intact later today. saving settings data causes a noticeable delay now, but i suppose that’s what it is. i can look out for the ASR menu hiding, but IIRC i ran into similar issues once, and couldn’t figure it out.

the KOMA/Common ground workshop yesterday was ok fun, btw. i hung out there for a little while, lots of (100% male) SMD newbies but except one guy whose module mysteriously wouldn’t want to work, it all went well.

**Comment by mxmxmx** [comment]
ps.

found a quick fix for the menu hiding thing: 
https://github.com/mxmxmx/O_C/commit/cb45a199d32ce1169c4c9eae45cf2c7ecce19968 <https://github.com/mxmxmx/O_C/commit/cb45a199d32ce1169c4c9eae45cf2c7ecce19968>

btw, i was just looking at QQ and was wondering what’s the expected behaviour when trigger = continous *and* internal CV sources are enabled?

**Comment by mxmxmx** [comment]
ps.

so i’ve merged your commits and the dual quantizer into this:
https://github.com/mxmxmx/O_C/tree/v1.2_test <https://github.com/mxmxmx/O_C/tree/v1.2_test>

this also adds:
- rearranged start-up delays, to hopefully make things somewhat more robust
- [ASR] ‘fix’ for ASR menu (hide options)
- [QQ] re-use trigger inputs for octave offset when trigger source == continuous  (as requested by "timoka". seems to work here. offsets will only happen if/when the pitch changed; tracking the inputs continuously didn’t give very good results / would be impossible to time properly)

**Comment by timchurches** [comment]
On 18 December 2016 at 20:24, mxmxmx <notifications@github.com> wrote:

> oh, i guess i misunderstood the consequences of changing the eeprom
> settings then. there should be no difference in terms of settings data
> between the sequencer branch and the DQ_test branch.
> i just merged your commits into that branch, too.
>

OK, I can spend most of tomorrow afternoon testing the v1.2beta code.


>
> i can double-check the calibration stays intact later today. saving
> settings data causes a noticeable delay now, but i suppose that’s what it
> is. i can look out for the ASR menu hiding, but IIRC i ran into similar
> issues once, and couldn’t figure it out.


Yes, I noticed the delay too, but then, it'snot really a
performance-oriented module.


>
> the KOMA/Common ground workshop yesterday was ok fun, btw. i hung out
> there for a little while, lots of (100% male) SMD newbies but except one
> guy whose module mysteriously wouldn’t want to work, it all went well.
>

Always a relief and gratifying when at least the majority of modules work.
I helped with one such workshop, building Mutable CV Pals (which are as
simple as it gets), and was very relieved when they all worked. And there
were even two female participants. But yeah, gender balance is an issue,
for sure.

Tim C

**Comment by timchurches** [comment]
On 18 December 2016 at 21:03, mxmxmx <notifications@github.com> wrote:

> ps.
>
> found a quick fix for the menu hiding thing:
> https://github.com/mxmxmx/O_C/commit/cb45a199d32ce1169c4c9eae45cf2c
> 7ecce19968 <https://github.com/mxmxmx/O_C/commit/
> cb45a199d32ce1169c4c9eae45cf2c7ecce19968>
>

OK, thanks! I should add a similar hack to the H1200 settings I added. I'll
do that tomorrow while testing the v1.2 merged code and send you a new pull
request.


>
> btw, i was just looking at QQ and was wondering what’s the expected
> behaviour when trigger = continous *and* internal CV sources are enabled?


Nothing. The internal CV sources only work with external triggers. There's
a not about that in the documentation (it could be more prominent, I
suppose).

Tim C

**Comment by timchurches** [comment]
On 19 December 2016 at 00:05, mxmxmx <notifications@github.com> wrote:

> ps.
>
> so i’ve merged your commits and the dual quantizer into this:
> https://github.com/mxmxmx/O_C/tree/v1.2_test <https://github.com/mxmxmx/O_
> C/tree/v1.2_test>
>
> this also adds:
> - rearranged start-up delays, to hopefully make things somewhat more robust
> - [ASR] ‘fix’ for ASR menu (hide options)
> - [QQ] re-use trigger inputs for octave offset when trigger source ==
> continuous (as requested by "timoka". seems to work here. offsets will only
> happen if/when the pitch changed; tracking the inputs continuously didn’t
> give very good results / would be impossible to time properly)


OK, sounds good. I will test it tomorrow and report back. I'm still working
on the v1.2 documentation - I'll finish it tonight, I hope.

Tim C

**Comment by mxmxmx** [comment]
> > btw, i was just looking at QQ and was wondering what’s the expected
> > behaviour when trigger = continous *and* internal CV sources are enabled?
> 
> 
> Nothing. The internal CV sources only work with external triggers. There's
> a not about that in the documentation (it could be more prominent, I
> suppose)

ah, i see. 

and cool, i can do a little more testing tomorrow, too. 
just pushed another few changes, just some house-keeping. the octave+/- stuff in continuous mode seems to work, but i might have broken something in the process. (though it doesn’t look lke it, thus far)

**Pull request merged**
